<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FreelancePlatform.Domain\FreelancePlatform.Domain.csproj" />
    <ProjectReference Include="..\FreelancePlatform.DAL\FreelancePlatform.DAL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
